### ISSUE TITLE
Reword / Explain more in depth changing of reducers

### ISSUE THREAD

**Issue by graciemcguire** [learn-co-curriculum/react-hooks-redux-intro-to-redux-codealong#2]
### Canvas Link

https://learning.flatironschool.com/courses/4182/assignments/126573?module_item_id=262184

### Concern

> Ok, so getting our application to re-render takes a bit of work, and were going to go into greater depth in the next sections. In the meantime, let's get some feedback. First, let's log our action and the new state. So we'll change the reducer to the following:
`./src/features/ShoppingList/shoppingListSlice.js`
>

The `./src/features/ShoppingList/shoppingListSlice.js` path / file has not been provided which could lead to confusion for students. We should either have them create this path or change to the already mentioned `counterSlice`

**Comment by ihollander** [comment]
Looks to me like this should reference the existing `features/counter/counterSlice.js` file instead of making a new file.

**Comment by graciemcguire** [comment]
Agreed!
